#!/bin/bash


sudo docker run --net=host \
		-it -d \
		-w /opt/TheSkyX/ \
		--rm \
	        --env="DISPLAY" \
		--volume="$HOME/.Xauthority:/root/.Xauthority:rw" \
	        --volume="/run/udev/data:/run/udev/data" \
		--volume="/lib/modules/5.4.32-rockchip64:/lib/modules/5.4.32-rockchip64" \
		--privileged \
		theskyx xterm
